name: Python application start

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Ejecutar la app
      run: |
        python app.py

    - name: Test with pytest
      run: |
        pytest

    - name: Simulación del deploy
      run: |
        echo "Simulando despliegue de la aplicación"

    - name: Construir la imagen de Docker
      run: |
        docker build -t ghcr.io/yajanuha597/hello-yajanuha:1.0.0 .

    - name: Login en GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publicar la imagen
      run: |
        docker push ghcr.io/yajanuha597/hello-yajanuha:1.0.0